---
name: CI

on:
  pull_request:
    branches: main

env:
  ENV: test
  K8S_VERSION: 1.18

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tooling
        run: |
          pip install cookiecutter yamllint
      - name: Test cookiecutter
        run: |
          cookiecutter . --no-input
      - name: Lint check yaml files
        uses: ibiqlik/action-yamllint@v3
        with:
          format: parsable
          strict: true
          file_or_dir: 'example-api/.github/workflows/*.yml'
          config_data: |
            extends: default
            rules:
              new-line-at-end-of-file: disable
              trailing-spaces:
                level: warning
              line-length: disable
              truthy: disable