version: "3.7"
services:
  app:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: asteristics-app
    env_file:
      - ./.env
    volumes:
      - ./docker/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./storage/app/public:/var/www/storage/app/public
      - ./storage/logs:/var/www/storage/logs
  nginx:
      image: nginx:alpine
      container_name: asteristics-nginx
      restart: unless-stopped
      ports:
          - 8000:80
      volumes:
          - ./docker/nginx:/etc/nginx/conf.d/
